POST http://localhost:8085/usuario/cadastrar
Content-Type: application/json

###
DELETE http://localhost:8085/deletarUsuario/1

###
GET http://localhost:8085/buscarUsuarios

###
POST http://localhost:8085/teste
Content-Type: application/json

{
    "nome": "Gabriel",

}
###
POST http://localhost:8085/cadastrarUsuario?nome=eduardo&cpf=11018864989&dataNascimento=a&cep=a&senha=b&email=c